---
- hosts: all
  remote_user: t
  tasks:
          - name: install pkg
            apt: pkg=grub-theme-tmaxlinux state=installed update_cache=true
            become: yes
            become_method: sudo
            become_user: root
